version: '3.8'

services:
  run-api-locally:
    depends_on:
      - tourmanique-api
      - tourmanique-api-s3

  tourmanique-api:
    build:
      context: .
    command: poetry run flask run
    volumes:
      - .:/app-workspace
    ports:
      - "7501:5000"
    env_file:
      - .env
    depends_on:
      - test-db

  tourmanique-api-postgres:
    env_file:
      - .env
    ports:
      - "7510:5432"

  test-db:
    container_name: test-db
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - test-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      timeout: 10s
      interval: 10s
      retries: 3
    networks:
      - tourmanique-net
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test_db"
    ports:
      - "65432:5432"

  tourmanique-api-s3:
    container_name: tourmanique-api-s3
    image: minio/minio:latest
    command: server /data --console-address ":7001"
    restart: always
    ports:
      - "7511:9000"
      - "7512:7001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./s3-data:/data
    networks:
      - tourmanique-net

  tourmanique-api-rabbitmq:
    env_file:
      - .env
    ports:
      - "7513:5672"
      - "7514:15672"

volumes:
  test-db-data: