version: '3.8'

services:
  run-api-locally:
    container_name: tourmanique-api-local-starter
    restart: "no"
    image: tianon/true
    depends_on:
      - tourmanique-api
      - tourmanique-api-postgres
      - tourmanique-api-rabbitmq

  tourmanique-api:
    container_name: tourmanique-api
    image: tourmanique-api:latest
    restart: unless-stopped
    networks:
      - tourmanique-net

  tourmanique-api-postgres:
    container_name: tourmanique-api-postgres
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - tourmanique-api-postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      timeout: 10s
      interval: 10s
      retries: 3
    networks:
      - tourmanique-net


  tourmanique-api-rabbitmq:
    container_name: tourmanique-api-rabbitmq
    image: rabbitmq:3.9.13-management-alpine
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - tourmanique-net


volumes:
  tourmanique-api-postgres-data:

networks:
  tourmanique-net:
    driver: bridge
